// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package sensor

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type probeEvent struct {
	_           structs.HostLayout
	Pid         uint32
	Ppid        uint32
	TimestampNs uint64
	EventType   uint32
	Comm        [16]int8
	Filename    [256]int8
	ConnectPort uint32
	ConnectIp   uint32
	_           [4]byte
	WriteBytes  uint64
	WriteFd     int32
	_           [4]byte
}

// loadProbe returns the embedded CollectionSpec for probe.
func loadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load probe: %w", err)
	}

	return spec, err
}

// loadProbeObjects loads probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*probeObjects
//	*probePrograms
//	*probeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// probeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeSpecs struct {
	probeProgramSpecs
	probeMapSpecs
	probeVariableSpecs
}

// probeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeProgramSpecs struct {
	HandleConnect     *ebpf.ProgramSpec `ebpf:"handle_connect"`
	HandleExecve      *ebpf.ProgramSpec `ebpf:"handle_execve"`
	HandleOpen        *ebpf.ProgramSpec `ebpf:"handle_open"`
	HandleOpenat      *ebpf.ProgramSpec `ebpf:"handle_openat"`
	HandleProcessFork *ebpf.ProgramSpec `ebpf:"handle_process_fork"`
	HandleUnlinkat    *ebpf.ProgramSpec `ebpf:"handle_unlinkat"`
	HandleWrite       *ebpf.ProgramSpec `ebpf:"handle_write"`
}

// probeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeMapSpecs struct {
	AllowedPids *ebpf.MapSpec `ebpf:"allowed_pids"`
	Events      *ebpf.MapSpec `ebpf:"events"`
}

// probeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type probeVariableSpecs struct {
	UnusedEvent *ebpf.VariableSpec `ebpf:"unused_event"`
}

// probeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeObjects struct {
	probePrograms
	probeMaps
	probeVariables
}

func (o *probeObjects) Close() error {
	return _ProbeClose(
		&o.probePrograms,
		&o.probeMaps,
	)
}

// probeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeMaps struct {
	AllowedPids *ebpf.Map `ebpf:"allowed_pids"`
	Events      *ebpf.Map `ebpf:"events"`
}

func (m *probeMaps) Close() error {
	return _ProbeClose(
		m.AllowedPids,
		m.Events,
	)
}

// probeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probeVariables struct {
	UnusedEvent *ebpf.Variable `ebpf:"unused_event"`
}

// probePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type probePrograms struct {
	HandleConnect     *ebpf.Program `ebpf:"handle_connect"`
	HandleExecve      *ebpf.Program `ebpf:"handle_execve"`
	HandleOpen        *ebpf.Program `ebpf:"handle_open"`
	HandleOpenat      *ebpf.Program `ebpf:"handle_openat"`
	HandleProcessFork *ebpf.Program `ebpf:"handle_process_fork"`
	HandleUnlinkat    *ebpf.Program `ebpf:"handle_unlinkat"`
	HandleWrite       *ebpf.Program `ebpf:"handle_write"`
}

func (p *probePrograms) Close() error {
	return _ProbeClose(
		p.HandleConnect,
		p.HandleExecve,
		p.HandleOpen,
		p.HandleOpenat,
		p.HandleProcessFork,
		p.HandleUnlinkat,
		p.HandleWrite,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfeb.o
var _ProbeBytes []byte
